### PR TITLE
etcd with Docker vs Consul with Vagrant

### PR DESCRIPTION
**Pull request by wzli1214**
Team name : WZL & ZYL
Members: Weizhao Li & Ziyue Li

This is a post of etcd with Docker vs Consul with Vagrant. The section of **Deploy a 3-node etcd Cluster in Docker** is written by Weizhao Li, the section of **Set Up Consul Based on Vagrant** is written by Ziyue Li. 

In Deploy a 3-node etcd Cluster in Docker, Weizhao covered the introduction of etcd and Docker, the main idea of Raft algorithm, and he provided an experiment to show how to deploy etcd in Docker and how to set up a multi-node etcd cluster in Docker. Finally, he talked about the comparison of etcd and consul.

In Set Up Consul Based on Vagrant, Ziyue introduced Consul and provided a mini-experiment of Consul based on Vagrant

@twood02   @thelimeburner

### CODE REVIEW

**Comment by thelimeburner** [comment]
@wzli1214 @zli19 Do you think you can fix your merge conflict by removing:

```
.DS_Store
wiki/.DS_Store
wiki/http1-2httpsSSL/.DS_Store
```

Thanks!

**Comment by wzli1214** [comment]
Sure. How is it now?

Lucas Chaufournier <notifications@github.com> 于2020年5月13日周三 下午5:22写道：

**Comment by thelimeburner** [comment]
image

its still not working. I see the following

**Comment by thelimeburner** [comment]
try doing in the root directory:

```
git rm .DS_Store
git rm wiki/http1-2httpsSSL/.DS_Store
wiki/http1-2httpsSSL/images/.DS_Store
git commit -m "removed conflict"
git push
```

**Comment by wzli1214** [comment]
How about that? Is it still have the problem?

Lucas Chaufournier <notifications@github.com> 于2020年5月13日周三 下午5:30写道：

**Comment by thelimeburner** [comment]
I still see two more files for some reason: 

image

**Comment by wzli1214** [comment]
Can I try to add .DS_Store into the root .gitignore file?

Lucas Chaufournier <notifications@github.com> 于2020年5月13日周三 下午5:37写道：

**Comment by thelimeburner** [comment]
Yea i think thats a good idea.

**Comment by thelimeburner** [comment]
I think I fixed it. Hold on

**Comment by thelimeburner** [comment]
Yup its done. Thanks for your patience there! We're good to go

**Comment by wzli1214** [comment]
I think that might be a problem, my previous blog has .DS_Store file, but
it already merged into the official repo. Could you delete that?  I guess
this causes the conflict with my up to date repo

[image: image.png]

Lucas Chaufournier <notifications@github.com> 于2020年5月13日周三 下午5:41写道：

**Comment by wzli1214** [comment]
Thank you so much!

>

**Pull request merged**
